Controllers/BoardController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Net.Http.Headers;
using System.Web;
using System.IO;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters;
using System.Xml.Serialization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using dotNetMVCFutabaChan.Models;

namespace dotNetMVCFutabaChan.Controllers
{
    public class BoardController : Controller
    {

        public Guid ThreadGuid;

        private readonly IHostingEnvironment _hostingEnvironment;

        public BoardController(IHostingEnvironment environment)
        {
            _hostingEnvironment = environment;
        }

        /* 1. Create a new thread based on model. */
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult Index(MessageModel form, IFormFile imageFile)
        {
            // New guid for our thread.
            ThreadGuid = Guid.NewGuid();

            // New thread.
            ThreadModel thread = new ThreadModel();
            List<ThreadModel> threadList = new List<ThreadModel>();
            XmlSerializer xs = new XmlSerializer(typeof(List<ThreadModel>));
            Int64 maxThreadId = 0;

            // The index message for new thread.
            MessageModel msg = new MessageModel();
            List<MessageModel> msgList = new List<MessageModel>();
            XmlSerializer ms = new XmlSerializer(typeof(List<MessageModel>));
            double maxMsgId = 0;

            // Retrieve the largest index number for a thread which currently exists.
            if (System.IO.File.Exists(Path.Combine(_hostingEnvironment.ContentRootPath, "Threads/ThreadList.xml")))
            {
                // Load existing XML file as a List<threadmodel>.
                try
                {
                    using (TextReader tr = new StreamReader(Path.Combine(_hostingEnvironment.ContentRootPath, "Threads/ThreadList.xml")))
                    {
                        threadList = (List<ThreadModel>)xs.Deserialize(tr);
                    }
                }
                catch (System.Exception ex)
                {
                    throw ex;
                }

                // Find largest thread id. Done to maintain some level of superficial compatibility with existing chans.
                maxThreadId = threadList.Max(i => i.threadId) + 1;
            }

            // Create a thread.
            thread.threadId = maxThreadId;
            thread.threadGuid = ThreadGuid;
            thread.creationDate = DateTime.UtcNow;
            threadList.Add(thread);

            /*
             * Save it as XML file.
             * TODO: Check for directory, if it doesn't exist yet, create a directory 'Threads'.
             */
            try
            {
                if (!Directory.Exists(Path.Combine(_hostingEnvironment.ContentRootPath, "Threads")))
                {
                    Directory.CreateDirectory(Path.Combine(_hostingEnvironment.ContentRootPath, "Threads"));
                }

                if (!Directory.Exists(Path.Combine(_hostingEnvironment.ContentRootPath, "Logs")))
                {
                    Directory.CreateDirectory(Path.Combine(_hostingEnvironment.ContentRootPath, "Logs"));
                }

                using (TextWriter tw = new StreamWriter(Path.Combine(_hostingEnvironment.ContentRootPath, "Threads/ThreadList.xml")))
                {
                    xs.Serialize(tw, threadList);
                }

                Log("New thread was created.");
                ViewData["SuccessMessage"] = "Thread Created!";
            }
            catch (System.Exception ex)
            {
                ViewData["FailMessage"] = "Shit Happened!";
                throw ex;
            }

            // Create a directory for our new thread.
            if (!System.IO.Directory.Exists(Path.Combine(_hostingEnvironment.ContentRootPath, "Threads/" + ThreadGuid.ToString())))
            {
                try
                {
                    System.IO.Directory.CreateDirectory(Path.Combine(_hostingEnvironment.ContentRootPath, "Threads/" + ThreadGuid.ToString()));
                }
                catch (System.Exception ex)
                {

                    throw ex;
                }
            }

            /*
                We know for certain that this is a message with zero id in
                this particular thread so skip the check and just process the form.
            */
            msg.threadGuid = ThreadGuid;
            msg.msgId = maxMsgId;
            msg.name = form.name;
            msg.email = form.email;
            msg.subject = form.subject;
            // TODO: If no message is found, throw an error and get the fuck out of here.
            msg.msgContent = form.msgContent;
            msg.postDate = DateTime.UtcNow;
            msgList.Add(msg);

            // I probably want to validate the model.
            // if (ModelState.IsValid) {}

            // Try processing file if it exists.
            if (imageFile != null && imageFile.Length > 0)
            {
                var parsedContentDisposition = ContentDispositionHeaderValue.Parse(imageFile.ContentDisposition);
                string FilePath = parsedContentDisposition.FileName.Trim('"');
                string FileExtension = Path.GetExtension(FilePath);
                var fileRootPath = Path.Combine(_hostingEnvironment.WebRootPath, "images/threads/" + ThreadGuid.ToString() + "/");
                var fileNamePath = Path.Combine(_hostingEnvironment.WebRootPath, "images/threads/" + ThreadGuid.ToString() + "/" + msg.msgId.ToString() + FileExtension);
                var thumbnailNamePath = Path.Combine(_hostingEnvironment.WebRootPath, "images/threads/" + ThreadGuid.ToString() + "/thumbnails/" + msg.msgId.ToString() + FileExtension);
                var fileUrl = Path.Combine("images/threads/" + ThreadGuid.ToString() + "/" + msg.msgId.ToString() + FileExtension);
                
                // Sandcastle which was never built.
                // msg.imgFile = fileUrl;
                msg.imgFile = msg.msgId.ToString() + FileExtension;

                if (!System.IO.Directory.Exists(fileRootPath))
                {
                    try
                    {
                        System.IO.Directory.CreateDirectory(Path.Combine(_hostingEnvironment.WebRootPath, "images/threads/" + ThreadGuid.ToString()));
                    }
                    catch (System.Exception ex)
                    {
                        throw ex;
                    }
                }

                using (var fs = new FileStream(fileNamePath, FileMode.Create))
                {
                    imageFile.CopyTo(fs);
                }

                // Check that we have a thumbnails directory where to write.
                if (!System.IO.Directory.Exists(Path.Combine(_hostingEnvironment.WebRootPath, "images/threads/" + ThreadGuid.ToString() + "/thumbnails")))
                {
                    try
                    {
                        System.IO.Directory.CreateDirectory(Path.Combine(_hostingEnvironment.WebRootPath, "images/threads/" + ThreadGuid.ToString() + "/thumbnails"));
                    }
                    catch (System.Exception ex)
                    {
                        throw ex;
                    }
                }

                // Ok, lets figure a way to create a thumbnail next.
                try
                {

                    using (Image<Rgba32> image = Image.Load(fileNamePath))
                    {
                        image.Mutate(x => x
                        .Resize(0, 300));
                        image.Save(thumbnailNamePath); // Automatic encoder selected based on extension.
                    }

                }
                catch (System.Exception i)
                {
                    throw i;
                }

            }

            // Save message as XML file.
            try
            {
                using (TextWriter tw = new StreamWriter(Path.Combine(_hostingEnvironment.ContentRootPath, "Threads/" + ThreadGuid.ToString() + "/" + ThreadGuid.ToString() + ".xml")))
                {
                    ms.Serialize(tw, msgList);
                }

                Log("New message was added to thread xxx.");
                ViewData["SuccessMessage"] = "Message Submitted!";
            }
            catch (System.Exception ex)
            {
                ViewData["FailMessage"] = "Shit Happened!";
                throw ex;
            }

            return this.RedirectToAction("Index", "Thread", new { guid = thread.threadGuid });
        }

        /* 2. List existing threads. */
        [HttpGet]
        public IActionResult Index(int? pageNum)
        {
            /* Ideal case:
                           if no number is specified, return shit from index number 0 up to 10 threads.
                           get number 1, return shit from index number 0 up to 10 threads.
                           get number 2, return shit from index number 9 up to 10 threads.
            */
            int page;
            int? threadNum = null;
            int threadsPerPage = 0;
            // ThreadModel thread = new ThreadModel();
            // MessageModel msg = new MessageModel();
            List<MessageModel> msgList = new List<MessageModel>();

Controllers/ImageController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using dotNetMVCFutabaChan.Models;

namespace dotNetMVCFutabaChan.Controllers
{
    public class ImageController : Controller
    {

        private readonly IHostingEnvironment _hostingEnvironment;

        public ImageController(IHostingEnvironment environment)
        {
            _hostingEnvironment = environment;
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult Index(PostModel post, IFormFile imageFile)
        {
            var uploads = Path.Combine(_hostingEnvironment.WebRootPath, "images");
            Guid guid = post.guid;
            DateTime postDate = post.postDate;
            string name = post.name;
            string email = post.email;
            string subtitle = post.subtitle;
            string comment = post.comment;
            string url = post.url;
            string host = post.host;
            string password = post.password;
            string imageFileName = post.imageFileName;
            string imageFileExtension = post.imageFileName;
            int thumbWidth = post.thumbWidth;
            int thumbHeight = post.thumbHeight;
            DateTime postTime = post.postTime;
            bool textOnly = post.textOnly;

            return View();
        }
    }
}

Views/Image/Index.cshtml
@model PostModel

@{
    ViewData["Title"] = "Image";
}

<div class="row">

    <img class="center-block" src="~/images/futa300.png" alt="Futaba .NET"> 

</div>

<hr />

<div class="row">

<h3>Post a thread</h3>

    @if (ViewData["InfoMessage"] != null) {
    <div class='alert alert-info' role='alert'>
        @ViewData["InfoMessage"]
    </div>
    }

    @if (ViewData["SuccessMessage"] != null) {
    <div class='alert alert-success' role='alert'>
        @ViewData["SuccessMessage"]
    </div>
    }
    
    @if (ViewData["FailMessage"] != null) {
    <div class="alert alert-danger" role="alert">
        @ViewData["FailMessage"]
    </div>
    }

</div>

@using (Html.BeginForm("Index", "Board", FormMethod.Post, new { enctype = "multipart/form-data", @class="form-horizontal form-background" }))
{
  @Html.ValidationSummary();
  
  <input type="hidden" name="mode" value="regist">
  <input type="hidden" name="MAX_FILE_SIZE" value="">
  <input type="hidden" name="resto" value="">
  
  <div class="form-group">
    @Html.LabelFor(p => p.name, new {@class="col-sm-2 control-label"})
    <div class="col-sm-10">
      @Html.TextBoxFor(p => p.name, new {@class="form-control", size = "30", placeholder="Nickname"})
    </div>
  </div>
  <div class="form-group">
    @Html.LabelFor(p => p.email, new {@class="col-sm-2 control-label"})
    <div class="col-sm-10">
    @Html.TextBoxFor(p => p.email, new {@class="form-control", size = "30", placeholder="Email Address"})
    </div>
  </div>
  <div class="form-group">
    @Html.LabelFor(p => p.subtitle, new {@class="col-sm-2 control-label"})
    <div class="col-sm-10">
      @Html.TextBoxFor(p => p.subtitle, new {@class="form-control", size = "35", placeholder="Subtitle"})
    </div>
  </div>
  <div class="form-group">
    @Html.LabelFor(p => p.comment, new {@class="col-sm-2 control-label"})
    <div class="col-sm-10">
      @Html.TextAreaFor(p => p.comment, new {@class="form-control", cols = "48", rows = "4", wrap = "soft", placeholder="Comment"})
    </div>
  </div>
  <div class="form-group">    
    <label for="attachedfile" class="col-sm-2 control-label">Attached File</label>
     <div class="col-sm-10">
       <input id="attachedfile" type="file" size="35">
     </div> 
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
            @Html.CheckBoxFor(p => p.textOnly) Text Only Thread
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    @Html.LabelFor(p => p.password, new {@class="col-sm-2 control-label"})
     <div class="col-sm-6">
       @Html.TextBoxFor(p => p.password, new {@class="form-control", size = "8", maxlength = "8"})
       <p class="help-block">(Use less than 8 alphanumeric characters)</p>
     </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" value="Submit" class="btn btn-default">Post</button>
    </div>
  </div>
}

<div class="row">

<h3>Threads</h3>

<table>

  <tr>
    <th></th>
  </tr>

  <tr>
    <td></td>
  </tr>

</table>


</div>